image: registry.gitlab.com/mvglasow/android-gitlab-ci:master

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

assembleDebug:
  stage: build
  script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - mkdir -p $GRADLE_USER_HOME
    - chmod +x ./gradlew
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - build/outputs/

# GitLab Pages

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master
